#!/bin/bash

prob="$(basename "${PWD}")"
if [[ -f "${prob}.py" ]]; then
  python3.7 "${prob}.py" <"${prob}.in" >"${prob}.actualout"
elif [[ -f "${prob}.cpp" ]]; then
  g++ "${prob}.cpp" -o "${prob}"
  ./"${prob}" <"${prob}.in" >"${prob}.actualout"
fi
diff -u "${prob}.actualout" "${prob}.out"
